# Generated by Django 4.1.3 on 2022-12-03 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('preview', models.TextField(max_length=500)),
                ('text', models.TextField()),
                ('score', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('picture_url', models.TextField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
