# Generated by Django 4.1.3 on 2022-12-03 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_delete_testmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='Articles',
        ),
    ]
